using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Duxel.Core.Dsl.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class DslBindableSourceGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Duxel.Core.Dsl.DslBindableAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, ct) => ExtractBindableType(ctx, ct))
            .Where(static t => t is not null)
            .Select(static (t, _) => t!);

        context.RegisterSourceOutput(candidates, static (spc, model) =>
        {
            var source = GenerateExtensionMethod(model);
            spc.AddSource($"{model.TypeName}DslBindable.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static BindableTypeModel? ExtractBindableType(GeneratorAttributeSyntaxContext ctx, System.Threading.CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        var properties = new List<PropertyModel>();

        foreach (var member in typeSymbol.GetMembers())
        {
            ct.ThrowIfCancellationRequested();

            if (member is not IPropertySymbol prop) continue;
            if (prop.IsStatic) continue;
            if (prop.DeclaredAccessibility is not Accessibility.Public) continue;
            if (prop.GetMethod is null) continue;
            if (prop.IsIndexer) continue;

            var propType = prop.Type;
            var conversion = GetStringConversion(propType);

            properties.Add(new PropertyModel(prop.Name, conversion));
        }

        if (properties.Count is 0)
            return null;

        var containingNamespace = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : typeSymbol.ContainingNamespace.ToDisplayString();

        var fullyQualifiedName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        return new BindableTypeModel(
            typeSymbol.Name,
            fullyQualifiedName,
            containingNamespace,
            properties.ToImmutableArray());
    }

    private static StringConversion GetStringConversion(ITypeSymbol type)
    {
        if (type.SpecialType is SpecialType.System_String)
            return StringConversion.Direct;

        if (type.SpecialType is SpecialType.System_Boolean)
            return StringConversion.BoolToString;

        if (type.SpecialType is
            SpecialType.System_Byte or SpecialType.System_SByte or
            SpecialType.System_Int16 or SpecialType.System_UInt16 or
            SpecialType.System_Int32 or SpecialType.System_UInt32 or
            SpecialType.System_Int64 or SpecialType.System_UInt64 or
            SpecialType.System_Single or SpecialType.System_Double or
            SpecialType.System_Decimal)
            return StringConversion.InvariantToString;

        return StringConversion.ToString;
    }

    private static string GenerateExtensionMethod(BindableTypeModel model)
    {
        var sb = new StringBuilder(1024);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine("using Duxel.Core.Dsl;");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"Duxel.Core.Dsl.Generator\", \"1.0\")]");
        sb.AppendLine($"public static class {model.TypeName}DslBindableExtensions");
        sb.AppendLine("{");

        // BindObjectList with default display func (ToString)
        sb.AppendLine($"    public static UiDslValueBinder BindObjectList(this UiDslValueBinder binder, string id, IReadOnlyList<{model.FullyQualifiedName}> list)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return binder.BindList(id, list, static item => item?.ToString() ?? string.Empty, PropertyAccessor);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // BindObjectList with custom display func
        sb.AppendLine($"    public static UiDslValueBinder BindObjectList(this UiDslValueBinder binder, string id, IReadOnlyList<{model.FullyQualifiedName}> list, Func<{model.FullyQualifiedName}, string> displayFunc)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return binder.BindList(id, list, displayFunc, PropertyAccessor);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Static property accessor
        sb.AppendLine($"    private static string? PropertyAccessor({model.FullyQualifiedName} item, string propertyName)");
        sb.AppendLine("    {");
        sb.AppendLine("        return propertyName switch");
        sb.AppendLine("        {");

        foreach (var prop in model.Properties)
        {
            var accessor = prop.Conversion switch
            {
                StringConversion.Direct => $"item.{prop.Name}",
                StringConversion.BoolToString => $"item.{prop.Name} ? \"true\" : \"false\"",
                StringConversion.InvariantToString => $"item.{prop.Name}.ToString(CultureInfo.InvariantCulture)",
                _ => $"item.{prop.Name}?.ToString() ?? string.Empty",
            };
            sb.AppendLine($"            \"{prop.Name}\" => {accessor},");
        }

        sb.AppendLine("            _ => null,");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

internal sealed record BindableTypeModel(
    string TypeName,
    string FullyQualifiedName,
    string? Namespace,
    ImmutableArray<PropertyModel> Properties);

internal sealed record PropertyModel(string Name, StringConversion Conversion);

internal enum StringConversion
{
    Direct,
    BoolToString,
    InvariantToString,
    ToString,
}
