using System.Globalization;
using System.Text;

namespace Duxel.Core.Dsl;

/// <summary>
/// Generates C# source code from a <see cref="UiThemeDef"/>.
/// The generated code creates a static property returning a <see cref="UiTheme"/> instance.
/// </summary>
public static class UiThemeCompiler
{
    public static string GenerateCSharp(string @namespace, UiThemeDef themeDef)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(@namespace);
        ArgumentNullException.ThrowIfNull(themeDef);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Duxel.Core;");
        sb.AppendLine();
        sb.AppendLine($"namespace {@namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static partial class Themes");
        sb.AppendLine("{");

        var safePropertyName = SanitizeIdentifier(themeDef.Name);
        sb.AppendLine($"    public static UiTheme {safePropertyName}");
        sb.AppendLine("    {");
        sb.AppendLine("        get");
        sb.AppendLine("        {");

        // Base preset
        var baseLine = themeDef.BasePreset?.ToLowerInvariant() switch
        {
            null or "" or "windows11" or "win11" => "var theme = UiWindows11Design.CreateTheme();",
            "windows11dark" or "win11dark" => "var theme = UiWindows11Design.CreateDarkTheme();",
            "dark" => "var theme = UiTheme.ImGuiDark;",
            "light" => "var theme = UiTheme.ImGuiLight;",
            "classic" => "var theme = UiTheme.ImGuiClassic;",
            var preset => throw new InvalidOperationException($"Unknown theme base preset: {preset}."),
        };
        sb.Append("            ").AppendLine(baseLine);

        // Overrides
        foreach (var entry in themeDef.Overrides)
        {
            sb.Append("            theme[UiStyleColor.")
              .Append(entry.Color)
              .Append("] = new UiColor(0x")
              .Append(entry.Value.Rgba.ToString("X8"))
              .AppendLine(");");
        }

        sb.AppendLine("            return theme;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static UiCompiledDesign {safePropertyName}Design");
        sb.AppendLine("    {");
        sb.AppendLine("        get");
        sb.AppendLine("        {");
        sb.AppendLine("            var design = \"" + EscapeString(themeDef.BasePreset ?? string.Empty) + "\".ToLowerInvariant() switch");
        sb.AppendLine("        {");
        sb.AppendLine($"            \"\" or \"windows11\" or \"win11\" => UiCompiledDesign.Windows11 with {{ Theme = {safePropertyName} }},");
        sb.AppendLine($"            \"windows11dark\" or \"win11dark\" => UiCompiledDesign.Windows11Dark with {{ Theme = {safePropertyName} }},");
        sb.AppendLine($"            \"dark\" or \"light\" or \"classic\" => new UiCompiledDesign({safePropertyName}, UiStyle.Default, UiDesignTokens.Default),");
        sb.AppendLine("            var preset => throw new InvalidOperationException($\"Unknown theme base preset: {preset}.\"),");
        sb.AppendLine("        };");
        sb.AppendLine("            var tokens = design.Tokens;");
        foreach (var entry in themeDef.DesignTokenOverrides)
        {
            sb.Append("            tokens = tokens with { ")
              .Append(entry.Token)
              .Append(" = ")
              .Append(FormatFloat(entry.Value))
              .AppendLine("f };");
        }
        sb.AppendLine("            return design with { Tokens = tokens };");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Applies the parsed theme definition onto a base <see cref="UiTheme"/> at runtime.
    /// Useful for development-time hot-reload without source generation.
    /// </summary>
    public static UiTheme Apply(UiThemeDef themeDef)
    {
        ArgumentNullException.ThrowIfNull(themeDef);

        var theme = themeDef.BasePreset?.ToLowerInvariant() switch
        {
            null or "" or "windows11" or "win11" => UiWindows11Design.CreateTheme(),
            "windows11dark" or "win11dark" => UiWindows11Design.CreateDarkTheme(),
            "dark" => UiTheme.ImGuiDark,
            "light" => UiTheme.ImGuiLight,
            "classic" => UiTheme.ImGuiClassic,
            var preset => throw new InvalidOperationException($"Unknown theme base preset: {preset}."),
        };

        foreach (var entry in themeDef.Overrides)
        {
            theme[entry.Color] = entry.Value;
        }

        return theme;
    }

    public static UiCompiledDesign ApplyDesign(UiThemeDef themeDef)
    {
        ArgumentNullException.ThrowIfNull(themeDef);

        var theme = Apply(themeDef);
        var design = themeDef.BasePreset?.ToLowerInvariant() switch
        {
            null or "" or "windows11" or "win11" => UiCompiledDesign.Windows11 with { Theme = theme },
            "windows11dark" or "win11dark" => UiCompiledDesign.Windows11Dark with { Theme = theme },
            "dark" or "light" or "classic" => new UiCompiledDesign(theme, UiStyle.Default, UiDesignTokens.Default),
            var preset => throw new InvalidOperationException($"Unknown theme base preset: {preset}."),
        };

        var tokens = design.Tokens;
        foreach (var entry in themeDef.DesignTokenOverrides)
        {
            tokens = SetDesignToken(tokens, entry.Token, entry.Value);
        }

        return design with { Tokens = tokens };
    }

    private static UiDesignTokens SetDesignToken(UiDesignTokens tokens, UiDesignToken token, float value)
        => token switch
        {
            UiDesignToken.WindowCornerRadius => tokens with { WindowCornerRadius = value },
            UiDesignToken.ControlCornerRadius => tokens with { ControlCornerRadius = value },
            UiDesignToken.ControlBorderWidth => tokens with { ControlBorderWidth = value },
            UiDesignToken.ControlPressedOffsetY => tokens with { ControlPressedOffsetY = value },
            UiDesignToken.InputCornerRadius => tokens with { InputCornerRadius = value },
            UiDesignToken.ToggleCornerRadius => tokens with { ToggleCornerRadius = value },
            UiDesignToken.ProgressCornerRadius => tokens with { ProgressCornerRadius = value },
            UiDesignToken.FocusRingThickness => tokens with { FocusRingThickness = value },
            _ => tokens,
        };

    private static string SanitizeIdentifier(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (var ch in name)
        {
            if (char.IsLetterOrDigit(ch) || ch is '_')
            {
                sb.Append(ch);
            }
        }

        if (sb.Length is 0 || char.IsDigit(sb[0]))
        {
            sb.Insert(0, '_');
        }

        return sb.ToString();
    }

    private static string EscapeString(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string FormatFloat(float value) => value.ToString("0.########", CultureInfo.InvariantCulture);
}
