using System.Text;

namespace Duxel.Core.Dsl;

/// <summary>
/// Generates C# source code from a <see cref="UiThemeDef"/>.
/// The generated code creates a static property returning a <see cref="UiTheme"/> instance.
/// </summary>
public static class UiThemeCompiler
{
    public static string GenerateCSharp(string @namespace, UiThemeDef themeDef)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(@namespace);
        ArgumentNullException.ThrowIfNull(themeDef);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Duxel.Core;");
        sb.AppendLine();
        sb.AppendLine($"namespace {@namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static partial class Themes");
        sb.AppendLine("{");

        var safePropertyName = SanitizeIdentifier(themeDef.Name);
        sb.AppendLine($"    public static UiTheme {safePropertyName}");
        sb.AppendLine("    {");
        sb.AppendLine("        get");
        sb.AppendLine("        {");

        // Base preset
        var baseLine = themeDef.BasePreset?.ToLowerInvariant() switch
        {
            "light" => "var theme = UiTheme.ImGuiLight;",
            "classic" => "var theme = UiTheme.ImGuiClassic;",
            _ => "var theme = UiTheme.ImGuiDark;",
        };
        sb.Append("            ").AppendLine(baseLine);

        // Overrides
        foreach (var entry in themeDef.Overrides)
        {
            sb.Append("            theme[UiStyleColor.")
              .Append(entry.Color)
              .Append("] = new UiColor(0x")
              .Append(entry.Value.Rgba.ToString("X8"))
              .AppendLine(");");
        }

        sb.AppendLine("            return theme;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Applies the parsed theme definition onto a base <see cref="UiTheme"/> at runtime.
    /// Useful for development-time hot-reload without source generation.
    /// </summary>
    public static UiTheme Apply(UiThemeDef themeDef)
    {
        ArgumentNullException.ThrowIfNull(themeDef);

        var theme = themeDef.BasePreset?.ToLowerInvariant() switch
        {
            "light" => UiTheme.ImGuiLight,
            "classic" => UiTheme.ImGuiClassic,
            _ => UiTheme.ImGuiDark,
        };

        foreach (var entry in themeDef.Overrides)
        {
            theme[entry.Color] = entry.Value;
        }

        return theme;
    }

    private static string SanitizeIdentifier(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (var ch in name)
        {
            if (char.IsLetterOrDigit(ch) || ch is '_')
            {
                sb.Append(ch);
            }
        }

        if (sb.Length is 0 || char.IsDigit(sb[0]))
        {
            sb.Insert(0, '_');
        }

        return sb.ToString();
    }
}
